/**
 * Patch registry for the Android/Termux compatibility fixes.
 *
 * GENERATED by `tools/extract-anchors.py` from `install-dsh.sh` — do not edit the
 * `pairs` by hand. Every pair is `[upstreamText, patchedText]` taken verbatim from
 * the installer (its steps 5, 7 and 8); the installer, not this file, is the
 * authority for the anchors.
 *
 * Each patched target carries a `dsh-android` marker at least once, which makes
 * the transformation strictly reversible: reverting substitutes
 * `patchedText -> upstreamText` and restores the upstream file byte for byte.
 *
 * Adding a fix is one entry here (or one entry in `src/checks.js` for an
 * install-time fact) plus its copy in the client dictionaries and `locale/`.
 *
 * @module src/patches
 */

/** Marker every patched region carries; its presence is what "applied" means. */
export const MARKER = 'dsh-android'

/** Runtime-toggleable file patches (kind `patch`). */
export const PATCH_ITEMS = [
	{
		id: "flock-session-lock",
		files: [
			{
				package: "@deepseek-ai/node-addon-system",
				file: "lib/flock.js",
				pairs: [
					["export async function tryLockExclusive(fd) {\n    const errno = await new Promise((resolve) => {\n        loadBinding().tryLock(fd, resolve);\n    });", "export async function tryLockExclusive(fd) {\n    /* dsh-android: android-arm64 无原生包可装，平台门禁降级为“无锁可用”。 */\n    try {\n        loadBinding();\n    }\n    catch (error) {\n        if (error?.code === 'ERR_FLOCK_UNSUPPORTED_PLATFORM')\n            return;\n        throw error;\n    }\n    const errno = await new Promise((resolve) => {\n        loadBinding().tryLock(fd, resolve);\n    });"],
				],
			},
		],
	},
	{
		id: "session-log-hardlink",
		files: [
			{
				package: "@deepseek-ai/dsh-session-persistence-jsonl",
				file: "lib/index.js",
				pairs: [
					["import { link, lstat, mkdir, mkdtemp, open, readFile, readdir, realpath, rm, stat, truncate } from \"node:fs/promises\";", "import { link, lstat, mkdir, mkdtemp, open, readFile, readdir, realpath, rename, rm, stat, truncate } from \"node:fs/promises\";"],
					["\tlink,\n\trm: (path) => rm(path, { force: true })", "\tlink: async (from, to) => {\n\t\t/* dsh-android: 禁 hardlink。改用 rename 原子发布，并保留原 link 的 EEXIST\n\t\t   语义——调用方靠它判断“目标已存在，未发布新代”。 */\n\t\tlet exists = true;\n\t\ttry {\n\t\t\tawait lstat(to);\n\t\t}\n\t\tcatch (error) {\n\t\t\tif (error?.code === \"ENOENT\") exists = false;\n\t\t\telse throw error;\n\t\t}\n\t\tif (exists) throw Object.assign(new Error(`EEXIST: file already exists, link '${from}' -> '${to}'`), { code: \"EEXIST\", errno: -17, syscall: \"link\", path: to, dest: from });\n\t\tawait rename(from, to);\n\t},\n\trm: (path) => rm(path, { force: true })"],
					["\t\t\tawait link(tmp, finalPath);", "\t\t\tawait rename(tmp, finalPath); /* dsh-android */"],
				],
			},
		],
	},
	{
		id: "attachment-hardlink",
		files: [
			{
				package: "@deepseek-ai/dsh-attachment-local",
				file: "lib/index.js",
				pairs: [
					["import { chmod, link, mkdir, open, readFile, rename, rm, unlink, writeFile } from \"node:fs/promises\";", "import { chmod, copyFile, link, mkdir, open, readFile, rename, rm, unlink, writeFile } from \"node:fs/promises\";"],
					["\t\t\tawait link(source, target);", "\t\t\tawait copyFile(source, target, constants.COPYFILE_EXCL); /* dsh-android: 源对象须保留 */"],
					["\t\t\tawait link(staged.path, target);", "\t\t\tawait rename(staged.path, target); /* dsh-android: 紧随其后即 unlink(staged.path) */"],
				],
			},
		],
	},
	{
		id: "app-boot-native-addon",
		files: [
			{
				package: "@deepseek-ai/dsh-app-boot",
				file: "lib/index.js",
				pairs: [
					["const addon = createRequire(import.meta.url)(\"node-addon-require-builtin\");", "const _dshReq = createRequire(import.meta.url);\n\tconst addon = { requireBuiltin: (id) => _dshReq(id) }; /* dsh-android: 原生 addon 无 android 预编译，改用 --expose-internals */"],
				],
			},
			{
				package: "@deepseek-ai/dsh-app-boot",
				file: "lib/worker/profile-resolution-bootstrap.js",
				pairs: [
					["const addon = createRequire(import.meta.url)(\"node-addon-require-builtin\");", "const _dshReq = createRequire(import.meta.url);\n\tconst addon = { requireBuiltin: (id) => _dshReq(id) }; /* dsh-android: 原生 addon 无 android 预编译，改用 --expose-internals */"],
				],
			},
		],
	},
	{
		id: "composer-enter",
		files: [
			{
				package: "@deepseek-ai/dsh-client-ui-conversation",
				file: "lib/client.js",
				pairs: [
					["\t\t\t\tevent?.preventDefault();\n\t\t\t\tif (event?.repeat === true) return true;", "\t\t\t\t/* dsh-android: 普通回车=换行（不发送），Ctrl/Cmd+Enter 或界面按钮才发送 */\n\t\t\t\tif (event === null || !(event.ctrlKey === true || event.metaKey === true)) return false;\n\t\t\t\tevent?.preventDefault();\n\t\t\t\tif (event?.repeat === true) return true;"],
					["\t\t\t\trootElement = root;\n", "\t\t\t\trootElement = root;\n\t\t\t\t/* dsh-android: 让输入法回车键显示“换行”而不是“发送” */\n\t\t\t\troot?.setAttribute(\"enterkeyhint\", \"newline\");\n"],
				],
			},
		],
	},
]

/** @returns {string[]} every package a patch item touches, for reporting. */
export function touchedPackages() {
	return [...new Set(PATCH_ITEMS.flatMap((item) => item.files.map((file) => file.package)))].sort()
}
